import mongoose from 'mongoose';

const manpowerSchema = new mongoose.Schema(
  {
    blockPlanningUnitName: { type: String, trim: true, required: true },
    district: { type: String, trim: true, required: true },
    additionalMedicalOfficerRegular: { type: String, trim: true },
    additionalMedicalOfficerContract: { type: String, trim: true },
    ayushDoctorRegular: { type: String, trim: true },
    ayushDoctorContract: { type: String, trim: true },
    healthSupervisorMale: { type: String, trim: true },
    healthSupervisorFemale: { type: String, trim: true },
    anm: { type: String, trim: true },
    firstAnm: { type: String, trim: true },
    secondAnm: { type: String, trim: true },
    bcm: { type: String, trim: true },
    otherLtSts: { type: String, trim: true },
    pharmacist: { type: String, trim: true },
    leprosyTbSupervisor: { type: String, trim: true },
    wardBoySweeper: { type: String, trim: true },
    driver: { type: String, trim: true },
    dataOperator: { type: String, trim: true },
    asha: { type: String, trim: true },
    ashaSangini: { type: String, trim: true },
    aroBmoCenter: { type: String, trim: true },
    anganwadi: { type: String, trim: true },
    anganwadiAssistant: { type: String, trim: true },
    urbanMo: { type: String, trim: true },
    urbanStaffNurse: { type: String, trim: true },
    urbanMedicalOfficerMale: { type: String, trim: true },
    urbanMedicalOfficerFemale: { type: String, trim: true },
    urbanAnm: { type: String, trim: true },
    urbanAsha: { type: String, trim: true },
    urbanHiredVaccinator: { type: String, trim: true },
    regularMoMale: { type: String, trim: true },
    regularMoFemale: { type: String, trim: true },
    contractMoMale: { type: String, trim: true },
    contractMoFemale: { type: String, trim: true },
    recordKey: { type: String, default: 'default', unique: true },
  },
  { timestamps: true },
);

export const Manpower = mongoose.model('Manpower', manpowerSchema);
