import mongoose from 'mongoose';

const microplanSchema = new mongoose.Schema(
  {
    blockPlanningUnitName: { type: String, trim: true, required: true },
    district: { type: String, trim: true, required: true },
    medicalOfficerName: { type: String, trim: true },
    medicalOfficerMobile: { type: String, trim: true },
    bpmBcpmName: { type: String, trim: true },
    bpmBcpmMobile: { type: String, trim: true },
    ioIccoAroName: { type: String, trim: true },
    ioIccoAroMobile: { type: String, trim: true },
    totalPopulation: { type: String, trim: true },
    ruralPopulation: { type: String, trim: true },
    urbanPopulation: { type: String, trim: true },
    revenueVillages: { type: String, trim: true },
    hamlets: { type: String, trim: true },
    totalVillagesWithHamlets: { type: String, trim: true },
    chcBlockPhcCount: { type: String, trim: true },
    phcCount: { type: String, trim: true },
    ppcCount: { type: String, trim: true },
    subCenterCount: { type: String, trim: true },
    vacantSubCenterCount: { type: String, trim: true },
    twoAnmSubCenterCount: { type: String, trim: true },
    deliveryPointSubCenterCount: { type: String, trim: true },
    coldChainPointCount: { type: String, trim: true },
    deepFreezerCount: { type: String, trim: true },
    ilrCount: { type: String, trim: true },
    largeColdBoxCount: { type: String, trim: true },
    smallColdBoxCount: { type: String, trim: true },
    vaccineCarrierCount: { type: String, trim: true },
    icePackCount: { type: String, trim: true },
    polioAvoCount: { type: String, trim: true },
    brickKilns: { type: String, trim: true },
    urbanSlums: { type: String, trim: true },
    nomads: { type: String, trim: true },
    constructionSites: { type: String, trim: true },
    otherSpecialAreas: { type: String, trim: true },
    settledAvo: { type: String, trim: true },
    recordKey: { type: String, default: 'default', unique: true },
  },
  { timestamps: true },
);

export const Microplan = mongoose.model('Microplan', microplanSchema);
